coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/*"
  - "docs/*"
  - "*.pyc"
  - "__pycache__"
  - "*.spec"
  - "build/*"
  - "dist/*"
  - ".venv/*"
  - ".github/*" 