# Configurações do sistema de atualização automática
update:
  interval: 300  # Intervalo em segundos (5 minutos)
  max_retries: 3  # Número máximo de tentativas em caso de erro

notifications:
  email:
    enabled: true
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    sender_email: ""  # Preencher com o e-mail do remetente
    recipient_email: ""  # Preencher com o e-mail do destinatário
    subject_prefix: "[Auto-Update]"

backup:
  enabled: true
  directory: "backups"
  max_backups: 5  # Número máximo de backups a manter 