# Configurações do sistema de atualização automática
update:
  interval: 300  # Intervalo em segundos (5 minutos)
  max_retries: 3  # Número máximo de tentativas em caso de erro

notifications:
  email:
    enabled: true  # Habilitado com os e-mails configurados
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    sender_email: "operacionaldpsp@gmail.com"
    recipient_email: "operacionaldpsp@gmail.com"
    subject_prefix: "[Auto-Update]"

backup:
  enabled: true
  directory: "backups"
  max_backups: 5  # Número máximo de backups a manter
  ignore_patterns:  # Padrões de arquivos a ignorar no backup
    - ".git"
    - ".venv"
    - "__pycache__"
    - "*.pyc"
    - "*.log"
    - "backups"
    - "node_modules"
    - "*.db"
    - "*.bat" 